version: '3'

services:
  #------------------------------------------------
  # Api
  #------------------------------------------------
  api:
    container_name: traxion-examples-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./prisma/schema.prisma:/app/prisma/schema.prisma:ro
