version: '3'

services:
  #------------------------------------------------
  # Database
  #------------------------------------------------
  database:
    container_name: traxion-examples-database
    image: postgres:15-alpine
    networks:
      - traxion-examples-database-network
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  #------------------------------------------------
  # Api
  #------------------------------------------------
  api:
    container_name: traxion-examples-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - traxion-examples-database-network
    volumes:
      - ./prisma/schema.prisma:/app/prisma/schema.prisma:ro

volumes:
  database-data:

networks:
  traxion-examples-database-network:
